=== ui-kreinhard/doc-xhtml/document.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="document">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="listOfSourceCode"/>
        <xs:element ref="tableOfContent"/>
        <xs:element ref="listOfFigures"/>
        <xs:element maxOccurs="unbounded" ref="include"/>
        <xs:element maxOccurs="unbounded" ref="chapter"/>
        <xs:element ref="bibliography"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="listOfSourceCode">
    <xs:complexType/>
  </xs:element>
  <xs:element name="tableOfContent">
    <xs:complexType/>
  </xs:element>
  <xs:element name="listOfFigures">
    <xs:complexType/>
  </xs:element>
  <xs:element name="chapter">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="content"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="include"/>
        <xs:element maxOccurs="unbounded" ref="section"/>
      </xs:sequence>
      <xs:attribute name="title" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="section">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="include"/>
        <xs:element ref="content"/>
        <xs:element ref="subsection"/>
      </xs:sequence>
      <xs:attribute name="title" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="subsection">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="content"/>
        <xs:element ref="subsubsection"/>
      </xs:sequence>
      <xs:attribute name="title" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="subsubsection">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="content"/>
      </xs:sequence>
      <xs:attribute name="title" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="bibliography">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="source"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="include">
    <xs:complexType>
      <xs:attribute name="src" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="content">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="source"/>
        <xs:element ref="figure"/>
        <xs:element ref="sourceCode"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="figure">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="source"/>
        <xs:element ref="title"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="sourceCode">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="content"/>
        <xs:element ref="title"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="source">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="title"/>
        <xs:element ref="author"/>
        <xs:element ref="sourceId"/>
        <xs:element ref="url"/>
      </xs:choice>
      <xs:attribute name="id" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="author" type="xs:NCName"/>
  <xs:element name="sourceId" type="xs:integer"/>
  <xs:element name="url" type="xs:NCName"/>
  <xs:element name="title" type="xs:string"/>
</xs:schema>

=== ui-kreinhard/doc-xhtml/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<document  
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="http://document.schema"
xmlns:xi="http://www.w3.org/2001/XInclude"
 xmlns:xlink="http://www.w3.org/1999/xlink"
xsi:schemaLocation="http://document.schema document.xsd">
        <include src="bar.xml"/>
	
	<chapter title="This is my first chapter">
		<content>
			Lets write some text
			<source id="1" />
		</content>
		<include src="bar.xml"/>
		<section title="section">
		<include src="bar.xml"/>
			<content>blablaba</content>
			<subsection title="subsection">
				<content>text hier - text da</content>
				<subsubsection title="ganz tief">
				
					<content>asdfasdf</content>
					
				</subsubsection>
			</subsection>
		</section>
	</chapter>
	<chapter title="This is my 2nd chaper">
		<content>
			Lets write some text
			<sourceCode>
				<content>class HelloWorldApp {
    public static void main(String[] args) {
        System.out.println("Hello World!"); // Display the string.
    }
}
</content>
				<title>Test source code</title>
			</sourceCode>
			interesting thing above and below
			<figure>
				<source>classDiagramChatExample.png</source>
				<title>title 0</title>
			</figure>
			<figure>
				<source>classDiagramChatExample.png</source>
				<title>title 0,1</title>
			</figure>
		</content>
		<section title="asdf">
			<content>blablaba</content>
			<subsection title="noch eins">
				<content>text hier - text da</content>
				<subsubsection title="ganz tief">
					<content>
						asdfasdf
						<figure>
							<source>classDiagramChatExample.png</source>
							<title>titel1</title>
						</figure>
						<figure>
							<source>classDiagramChatExample.png</source>
							<title>titel2</title>
						</figure>
					</content>
				</subsubsection>
			</subsection>
		</section>
		<section title="asdf">
			<content>
				blablaba
				<source id="2" />
				blabla
			</content>
			<subsection title="noch eins">
				<content>text hier - text da</content>
				<subsubsection title="ganz tief">
					<content>asdfasdf</content>
				</subsubsection>
			</subsection>
		</section>
		<section title="asdf">
			<content>blablaba</content>
			<subsection title="noch eins">
				<content>text hier - text da</content>
				<subsubsection title="ganz tief">
					<content>asdfasdf</content>
				</subsubsection>
			</subsection>
		</section>
		<section title="asdf">
			<content>blablaba</content>
			<subsection title="noch eins">
				<content>text hier - text da</content>
				<subsubsection title="ganz tief">
					<content>
						asdfasdf
						<figure>
							<source>classDiagramChatExample.png</source>
							<title>title 4</title>
						</figure>
					</content>
				</subsubsection>
			</subsection>
		</section>
	</chapter>
	<bibliography>
		<source>
			<sourceId>1</sourceId>
			<author>Karl</author>
			<url>wikipedia</url>
			<title>How to not write xml</title>
		</source>
		<source>
			<sourceId>2</sourceId>
			<author>Karl</author>
			<url>wikipedia</url>
			<title>How to write xml</title>
		</source>
	</bibliography>
</document>

=== ui-kreinhard/doc-xhtml/bar.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="http://document.schema"
xmlns:xi="http://www.w3.org/2001/XInclude"
 xmlns:xlink="http://www.w3.org/1999/xlink"
xsi:schemaLocation="http://document.schema document.xsd">
	<listOfSourceCode />
	<tableOfContent />
	<listOfFigures />
	<chapter title="included chapter">
	   <section title="included section">
	       <subsection title="included subsection">
	       <content>asdfasdfasdfasdfasdfasdfasdf</content>
	       </subsection>
	   </section>
	</chapter>
</document>
